mapbox/mapbox-maps-flutter

lib/src/map_widget.dart

Considering flutters posibility for calling build method on every frame as stated in the docs,
> This method can potentially be called in every frame and should not have any side effects beyond building a widget.
we can say that `MapWidget`s build method has side effects of calling `onMapCreated` callback which should be called only the first time map is created, which is already done from `onPlatformViewCreated` callback.
Fixes: #26 
Fixes: #57 
Fixes: #68

Fix mapCreated callback called on every build

---

CHANGELOG.md
lib/mapbox_maps_flutter.dart
pubspec.yaml

It is needed export the turf package, for use the **Postion** class and others. Otherwise, this package can't be used with the turfs types.

Export package turf.

---

CHANGELOG.md
example/integration_test/animation_test.dart
example/integration_test/annotations/circle_annotation_manager_test.dart
example/integration_test/annotations/circle_annotation_test.dart
example/integration_test/annotations/point_annotation_manager_test.dart
example/integration_test/annotations/point_annotation_test.dart
example/integration_test/annotations/polygon_annotation_manager_test.dart
example/integration_test/annotations/polygon_annotation_test.dart
example/integration_test/annotations/polyline_annotation_manager_test.dart
example/integration_test/annotations/polyline_annotation_test.dart
example/integration_test/projection_test.dart
example/ios/Podfile.lock
example/lib/full_map.dart
lib/src/style/layer/background_layer.dart
lib/src/style/layer/circle_layer.dart
lib/src/style/layer/fill_extrusion_layer.dart
lib/src/style/layer/fill_layer.dart
lib/src/style/layer/heatmap_layer.dart
lib/src/style/layer/hillshade_layer.dart
lib/src/style/layer/line_layer.dart
lib/src/style/layer/location_indicator_layer.dart
lib/src/style/layer/raster_layer.dart
lib/src/style/layer/sky_layer.dart
lib/src/style/layer/symbol_layer.dart
lib/src/style/style.dart

Properties that are set to expressions will return nulls. 
To retrieve such properties lower level style apis can be used at the moment, e.g. : `map.style.getStyleLayerProperty(LAYER, PROPERTY);`
Fixes #14 / MAPSFLT-89, cc @LjubiTech-Maxko

Fix getLayer on layers with expression properties. 

---

CHANGELOG.md
ios/Classes/CameraController.swift
lib/src/style/layer/background_layer.dart
lib/src/style/layer/circle_layer.dart
lib/src/style/layer/fill_extrusion_layer.dart
lib/src/style/layer/fill_layer.dart
lib/src/style/layer/heatmap_layer.dart
lib/src/style/layer/hillshade_layer.dart
lib/src/style/layer/line_layer.dart
lib/src/style/layer/location_indicator_layer.dart
lib/src/style/layer/raster_layer.dart
lib/src/style/layer/sky_layer.dart
lib/src/style/layer/symbol_layer.dart

Fixes #77.
Also fixed an issue when plugin on iOS maps doubles as ints when the there's no fraction part (e.g. double `1.0` arrives as int   `1`).

Fix camera.pixelsForCoordinates iOS implementation.

---

lib/src/mapbox_map.dart

Documentation update for `getElevation` function to indicate that elevation is only available if terrain is enabled.
Fixes: #82

Update documentation for getElevation

---

lib/src/map_widget.dart
lib/src/mapbox_map.dart

There is a memory leak if we add `onTapListener`, `onLongTapListener` or `onScrollListener` callbacks. `GestureListener` is set up but never disposed.
Also, considering the documentation for dispose method which states:
> Implementations of this method should end with a call to the inherited method, as in super.dispose().
I moved those calls to the end of the method.
Edit: Reverted MapWidget super.dispose() call because, I assume, widget is already disposed and unmounted while _controller.future is being awaiting for, which caused the following assertion `_MapWidgetState.dispose failed to call super.dispose.`
- Bug fix (non-breaking change)

Fix GestureListener not being disposed

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapsPlugin.kt
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/integration_test/compass_test.dart
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/Info.plist
example/pubspec.lock
ios/Classes/MapboxMapController.swift
ios/Classes/MapboxMapFactory.swift
ios/mapbox_maps_flutter.podspec
lib/src/map_widget.dart
lib/src/mapbox_map.dart
lib/src/mapbox_maps_platform.dart
pubspec.yaml

Memory leaks fixed with this pr : 
- [unsubscribed](https://github.com/mapbox/mapbox-maps-flutter/compare/yds-fix-memory-leaks?expand=1#diff-06381fce62147e22668fce21e996118ab467e38cdcbedeede6ae71dd686d8c3bR77) lifecycle observer to release MapView and other objects on java end
- reused MethodChannels instead of spawning new ones with every new Map created, since Flutter does not releases created MethodChannels. For that purpose introduced [SuffixesRegistry](https://github.com/mapbox/mapbox-maps-flutter/compare/yds-fix-memory-leaks?expand=1#diff-15b2331720a881719d558beae78491e3825309f1d6b4d37a85db56690f38f55cR193) that rotates suffixes when Map instances are created / destroyed. So worst case we have N `MethodChannel`s simultaneously when N Maps are displayed on the screen at the same time …

Fix multiple memory leaks

---

lib/src/pigeons/map_interfaces.dart
pubspec.yaml

This PR fixes typecasting crashes for nested collections in generated decoding code by adopting a forked version of Pigeon - https://github.com/evil159/packages
The plan is to use the fork for the time being while proposing this change to be adopted by the mainstream Pigeon.

Use forked Pigeon

---

.circleci/config.yml
.fastlane/Fastfile

This PR introduces following changes to the CircleCI config:
* update macOS runner to M1: `macos.m1.medium.gen1`
* update Xcode version to `15.0.0`
* use `circleci/macos` - mainly because it makes it easy to install Rosetta which is required for Flutter on M1
* use `gcp-cli` orb for `gcloud`(also update to the latest version: `449.0.0`)
* bump Flutter SDK version to `3.13.6`
* kick off firebase tests and wait the results on a small docker image(should be a bit cheaper I guess)
* remove duplicate code signing and build steps for iOS
This effectively halves iOS build time(~-50%), so now it is on par with Android(~5m), which results in a shorted turnaround time for the whole workflow(~10m now vs ~16m before).
Plus, saves a bit of time installing `glcould`(not sure how but the orb installs it …

Update CI config

---

ios/Classes/CompassController.swift

This PR removes one instance of >swift 5.9 -only syntax that makes iOS builds fail with Xcode 14.
Addresses https://github.com/mapbox/mapbox-maps-flutter/issues/264

[iOS] Fix swift 5.8 build error

---

pubspec.yaml

As per https://dart.dev/resources/dart-3-migration#dart-3-backwards-compatibility - if the lower bound is > 2.12.0 then the upper bound is interpreted to be <4.0.0.

Update dart sdk requirement

---

android/src/main/java/com/mapbox/maps/pigeons/FLTMapInterfaces.java
example/integration_test/camera_test.dart
example/ios/Podfile.lock
example/lib/camera.dart
ios/Classes/CameraController.swift
ios/Classes/Extensions.swift
ios/Classes/LocationController.swift
ios/Classes/MapEvents+JSON.swift
ios/Classes/MapInterfaces.h
ios/Classes/MapInterfaces.m
ios/Classes/MapboxMapController.swift
ios/Classes/MapboxMapFactory.swift
ios/Classes/MapboxOptionsController.swift
ios/Classes/StyleController.swift
ios/mapbox_maps_flutter.podspec
lib/src/events.dart
lib/src/mapbox_map.dart
lib/src/pigeons/gesture_listeners.dart
lib/src/pigeons/map_interfaces.dart
test/events_test.dart

1fdd691652e9020c7bbaac946eacd6c1231072dd Convert `StyleColor` to integer representation. In v11, `StyleColor` supports RGB(A), HSL(A), hex, and a raw string as shown [here](https://docs.mapbox.com/style-spec/reference/types/#color) for a moment, we support HSL(A) and RGB(A) only.
49605d6f306f89569951871ec16653e47cf2943c Add conformers for `_MapboxOptions` and `_MapboxMapsOptions` that is responsible for managing access token and map's configuration (previously known as ResourceOptionsManager).
Upstream https://github.com/mapbox/mapbox-maps-flutter-internal/pull/126

[v11] resolve build errors iOS

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/PointAnnotationController.kt
example/integration_test/annotations/point_annotation_test.dart
example/ios/Podfile.lock
ios/Classes/PointAnnotationController.swift

There was an error in conversion from FLT annotation to the native one - image would always get assigned a new, random name. I fixed that, as well as added image bitmap to annotations created by annotation manager.
Addresses: https://github.com/mapbox/mapbox-maps-flutter/issues/241, https://github.com/mapbox/mapbox-maps-flutter/issues/166

Fix point annotation image disappearing after update on iOS

---

lib/src/mapbox_maps_options.dart

This PR converts all getters/setters in `MapboxMapsOptions` to be static(it was overlooked). Plus, makes constructors of `MapboxMapsOptions` and `MapboxOptions` private, as these classes are not supposed to be initialized.

Make all methods of MapboxMapsOptions static

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt
example/ios/Podfile.lock

Fixes issue when initial camera options passed to `MapWidget` were ignored.

Fix initial camera options not being applied on Android

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt

As pointed out in the https://github.com/mapbox/mapbox-maps-flutter/issues/377#issuecomment-1904311347, incorrect index access to mapOptions in `MapboxMapFactory` create method could be causing blank map issues.
The following exception would be thrown:
`Unhandled Exception: PlatformException(error, java.lang.Double cannot be cast to java.util.ArrayList, null, java.lang.ClassCastException: java.lang.Double cannot be cast to java.util.ArrayList`
because it tried to access `pixelRatio` option at index 6 which is `Double` instead of `size` at index 5 which is `ArrayList<Double>` causing MapboxMapFactory to fail creating the map.

[Android] Fix MapOptions incorrect index access at map creation

---

CHANGELOG.md
example/integration_test/map_interface_test.dart
example/lib/animated_route.dart
example/pubspec.lock
example/pubspec.yaml
lib/mapbox_maps_flutter.dart
lib/src/map_widget.dart
lib/src/mapbox_maps_platform.dart
pubspec.yaml

* Adds a `androidHostingMode` construction parameter to `MapWidget`, allowing to configure the way map view is being hosted in Flutter.
* Changes the default hosting mode from Virtual Display to Hybrid Composition.
Latest Android 14 QPR beta 3 makes the map view to stop rendering on resume from background in Virtual Display mode, switching to Hybrid Composition helps[TODO: Link Android flutter ticket]. Similar issue with the latest update of Android 14 on Samsung Galaxy phones. https://github.com/flutter/flutter/issues/139039 https://github.com/flutter/flutter/issues/139630
Addresses: https://github.com/mapbox/mapbox-maps-flutter/issues/323 https://github.com/mapbox/mapbox-maps-flutter/issues/205
Not testable.

Configurable android view hosting mode

---

.circleci/config.yml

Updates following points in the CircleCI config:
* Removes Cocoapods workaround
* Updates latest Xcode version to 15.2
* Bumps Flutter SDK version to the latest(3.16.9)
* Bumps macOS orb to the latest version(2.4.1)
Cleanup and maintenance.

Update circle ci config

---

CHANGELOG.md
ios/Classes/GesturesController.swift

Re-wires `MapWidget`'s `onScroll` event to be triggered whenever pan gesture is began/moved/ended instead of triggering it only after pan ends(as it was before).
Alignment with the behavior on Android, addressing https://mapbox.atlassian.net/browse/MAPSFLT-170
This behavior is not covered by tests

[iOS] Fix onScroll being triggered only once at the end of pan gesture

---

.circleci/config.yml

Switch Android Firebase tests to be run on a Pixel 8 device.
After recent outage Pixel 6(our current) devices seem to be still stuck on Firebase.

Switch Android Firebase tests to Pixel 8

---

.circleci/config.yml

Switches iOS device tests to use iPhone 13 Pro.
Firebase recommendation.

Use iPhone 13 Pro for iOS device tests

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/CircleAnnotationMessager.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/GestureListeners.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/LogBackend.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PointAnnotationMessager.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PolygonAnnotationMessager.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PolylineAnnotationMessager.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/Settings.kt
example/integration_test/style/source/image_source_test.dart
example/integration_test/style/source/raster_source_test.dart
example/integration_test/style/source/rasterdem_source_test.dart
example/integration_test/style/source/vector_source_test.dart
example/lib/circle_annotations.dart
example/lib/cluster.dart
example/lib/point_annotations.dart
example/lib/polygon_annotations.dart
example/lib/polyline_annotations.dart

This PR utilizes `includeErrorClass` option released in Pigeon 17.1.0 to reuse `FlutterError` type instead of generating unique error type for each template.
Cleaner codegen on our side.

Reuse FlutterError in Kotlin

---

CHANGELOG.md
lib/src/mapbox_maps_options.dart

This PR marks `MapboxMapsOptions.get/setWorldview()` and `MapboxMapsOptions.get/setLanguage()` as experimental. 
This is a follow-up to the original PR: https://github.com/mapbox/mapbox-maps-flutter/pull/420.

Mark worldview and language configs as experimental

---

CHANGELOG.md
example/integration_test/camera_test.dart
example/lib/camera.dart
lib/src/mapbox_map.dart

This PR deprecates `cameraForCoordinates` API, which has been deprecated in GL-Native, iOS and maybe Android (?!)

Deprecate old camera api

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/LocationComponentController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LocationComponentMappings.kt
example/lib/location.dart
ios/Classes/LocationController.swift

Allows setting an empty byte array to puck's images, when this is set, the image will be disable on the puck
```
// This will use a puck with custom topImage, default bearing image and no shadow image
mapboxMap?.location.updateSettings(LocationComponentSettings(
enabled: true,
puckBearingEnabled: true,
locationPuck:
LocationPuck(locationPuck2D: DefaultLocationPuck2D(topImage: list, shadowImage: Uint8List.fromList([])))));
```

Allows setting empty byte array to remove puck's images

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapsPlugin.kt

Addresses the issue that was caused by the `maps-lifecycle` plugin being pulled to the build.
Normally it was excluded from the flutter plugin explicitly [here](https://github.com/mapbox/mapbox-maps-flutter/blob/main/android/build.gradle#L66), and instead lifecycle methods onStart/onStop/onDestroy were called directly on the MapView.
However, other 3-party plugins could still bring the dependency. 
The plugin then crashes internally within [ViewLifecycleOwner](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/ViewLifecycleOwner.kt#L69).
In this PR custom Lifecycle is implemented to manage MapView lifecycle calls, `maps-lifecycle` dependency is no longer excluded. 
Custom Lifecycle mirrors lifecycle of the hosting …

Fix crash due to lifecycle plugin.

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt
example/integration_test/style/style_test.dart
ios/Classes/StyleController.swift

Fixes `hasStyleImage` hanging and `getStyleImage` causing exception from Flutter's method channel on Android.

Fix style image methods hang&exception

---

CHANGELOG.md
example/assets/raster_array_layers.json
example/integration_test/all_test.dart
example/integration_test/map_interface_test.dart
example/integration_test/style/source/rasterarray_source_test.dart
lib/mapbox_maps_flutter.dart
lib/src/style/source/rasterarray_source.dart
lib/src/style/style.dart

This PR exposes `RasterArraySource`. Note that `rasterLayers` is a get-only property.
Parity with [iOS](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Generated/Sources/RasterArraySource.swift) and [Android](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterArraySource.kt) SDKs.

Expose Raster Array Source

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
example/integration_test/map_interface_test.dart
ios/Classes/MapboxMapController.swift
lib/src/mapbox_map.dart
lib/src/mapbox_maps_platform.dart

Adds `MapWidget.snapshot()` method allowing to capture a snapshot image of the current state of the map widget.
API parity with platform SDKs.

MapWidget snapshotting

---

CHANGELOG.md
lib/src/style/layer/background_layer.dart
lib/src/style/layer/circle_layer.dart
lib/src/style/layer/fill_extrusion_layer.dart
lib/src/style/layer/fill_layer.dart
lib/src/style/layer/heatmap_layer.dart
lib/src/style/layer/hillshade_layer.dart
lib/src/style/layer/line_layer.dart
lib/src/style/layer/location_indicator_layer.dart
lib/src/style/layer/raster_layer.dart
lib/src/style/layer/sky_layer.dart
lib/src/style/layer/symbol_layer.dart
lib/src/style/source/raster_source.dart
lib/src/style/source/rasterdem_source.dart
lib/src/style/source/vector_source.dart

Multi-word enum cases were not encoded/decoded properly - instead of the correct form e.g. `some-value` it would be `some_value` which would cause a PlatformException.
https://github.com/mapbox/mapbox-maps-flutter/issues/500, https://github.com/mapbox/mapbox-maps-flutter/issues/455, https://github.com/mapbox/mapbox-maps-flutter/issues/161, https://mapbox.atlassian.net/browse/MAPSFLT-206

Fix multiword enum cases encoding and decoding

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/EventHandler.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/SnapshotterMessenger.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/snapshotter/SnapshotterInstanceManager.kt
example/integration_test/snapshotter/snapshotter_test.dart
example/ios/Podfile.lock
example/lib/geojson_line.dart
example/lib/snapshotter.dart
example/pubspec.lock
ios/Classes/EventHandler.swift
ios/Classes/Generated/MapInterfaces.swift
ios/Classes/Generated/SnapshotterMessenger.swift
ios/Classes/MapboxMapController.swift
ios/Classes/MapboxMapFactory.swift
ios/Classes/Snapshotter/SnapshotterController.swift
ios/Classes/Snapshotter/SnapshotterInstanceManager.swift
lib/src/map_events.dart
lib/src/map_widget.dart
lib/src/snapshotter/snapshotter.dart
lib/src/snapshotter/snapshotter_messenger.dart
lib/src/style/source/rasterarray_source.dart

Fixes race condition in events when method call to subscribe to map events from dart side was competing with early map events.
The fix is to pass event types upon map widget initialization.
Bugfix.

Map events race condition fix

---

android/build.gradle
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/AttributionMappings.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LogoMappings.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/Settings.kt
example/integration_test/attribution_test.dart
example/integration_test/logo_test.dart
ios/Classes/AttributionController.swift
ios/Classes/Generated/Settings.swift
ios/Classes/LogoController.swift
lib/src/pigeons/settings.dart

Adds configuration options to configure map widget logo and attribution visibility.
Addresses: https://mapbox.atlassian.net/browse/MAPSFLT-207

Add option to enable/disable map widget attribution

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/mapbox_maps_flutter.podspec

Increases Maps SDK dependency version to 11.4.0 both on Android and iOS.

Bump maps sdk to 11.4.0

---

ios/Classes/MapboxMapController.swift

Removes accidentally committed camera overlay debug option from iOS.

Remove camera debug overlay from iOS code

---

example/integration_test/camera_test.dart
example/lib/empty_map_widget.dart
example/pubspec.lock
pubspec.yaml

Address #574 
We don't actually use `enum_to_string` even though we declare it as dependency, so it is safe to remove it.
This PR also fixes failing getCameraState test, by explicitly set camera to the map and not just use the default camera of the style, which might be subjected to change.

remove enum_to_string from deps

---

lib/src/turf_adapters.dart

It seems that named constructors are not inherited by our turf-derived types. This PR adds them back.
Addresses: https://github.com/mapbox/mapbox-maps-flutter/issues/594

Add missing constructors to turf-derived types

---

CHANGELOG.md
LICENSE
README.md
android/build.gradle
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/PolylineAnnotationEnumsExtensions.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PolylineAnnotationMessenger.kt
example/README.md
example/ios/Podfile.lock
example/pubspec.lock
example/pubspec.yaml
ios/Classes/EnumsMapping.swift
ios/Classes/Generated/PolylineAnnotationMessenger.swift
ios/mapbox_maps_flutter.podspec
lib/src/map_widget.dart
lib/src/pigeons/polyline_annotation_messenger.dart
pubspec.yaml

Expose `LineJoin.NONE`

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapInterfaceController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt
example/analysis_options.yaml
example/ios/Podfile.lock
example/lib/debug_options.dart
example/lib/main.dart
example/lib/model_layer.dart
example/lib/offline_map.dart
example/lib/traffic-route-line.dart
ios/Classes/Extensions.swift
ios/Classes/Generated/MapInterfaces.swift
ios/Classes/MapInterfaceController.swift
ios/Classes/MapboxMapController.swift
lib/src/mapbox_map.dart
lib/src/pigeons/map_interfaces.dart

Exposes native map debug options.
| Option | Description |
| ------ | ------------ |
| `tileBorders` | Edges of tile boundaries are shown as thick, red lines to help diagnose tile clipping issues. |
| `parseStatus` | Each tile shows its tile coordinate (x/y/z) in the upper-left corner. |
| `timestamps` | Each tile shows a timestamps with modified and expires dates or n/a if timestamp is not available. |
| `collision` | Edges of glyphs and symbols are shown as faint, green lines to help diagnose collision and label placement issues. |
| `overdraw` | Each drawing operation is replaced by a translucent fill. Overlapping drawing operations appear more prominent to help diagnose overdrawing. |
| `stencilClip` | The stencil buffer is shown instead of the color buffer. |
| `depthBuffer` | The …

Expose debug options

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/OfflineMapInstanceManager.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/TileStoreController.kt
example/ios/Podfile.lock
example/lib/offline_map.dart
ios/Classes/Extensions.swift
ios/Classes/Offline/OfflineMapInstanceManager.swift
ios/Classes/Offline/TileStoreController.swift

Add default `pixelRatio` for `TilesetDescriptorOptions`, so raster tileset can be loaded in offline mode. This also set `MapboxMapsOptions.tileStore` automatically on initialization of TileStore
Related PRs
- https://github.com/mapbox/mapbox-maps-android-internal/pull/2508
- https://github.com/mapbox/mapbox-maps-ios-internal/pull/2172

[offline] add default pixelRatio for TilesetDescriptorOptions

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt

This PR merges https://github.com/mapbox/mapbox-maps-flutter/pull/668. Additionally, android lifecycle and annotation dependencies were bumped in order to make this fix work.

fixes build for flutter 3.24.1 #668

---

.circleci/config.yml
example/lib/utils.dart
example/pubspec.lock

This PR bumps Flutter SDK version to `3.24.1` on CircleCI, plus bumps CircleCI orbs to their latest versions.
Keeping up with time.

Use Flutter SDK `3.24.1` on CI

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/GestureController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/GestureListeners.kt
example/lib/gestures.dart
ios/Classes/Extensions.swift
ios/Classes/Generated/GestureListeners.swift
ios/Classes/GesturesController.swift
lib/src/extensions.dart
lib/src/pigeons/gesture_listeners.dart

Add `GestureState` to `MapContentGestureContext` to indicate whether gesture has been started, its touches have changed or it has ended.
https://mapbox.atlassian.net/browse/MAPSFLT-235

Report GestureState in map gesture context

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/turf/TurfAdapters.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt
example/assets/from_crema_to_council_crest.geojson
example/integration_test/camera_test.dart
example/integration_test/style/source/geojson_source_test.dart
example/integration_test/style/style_test.dart
example/ios/Podfile.lock
example/ios/Runner/AppDelegate.swift
example/lib/empty_map_widget.dart
example/lib/geojson_line.dart
example/lib/offline_map.dart
example/pubspec.lock
ios/Classes/Generated/MapInterfaces.swift
ios/Classes/StyleController.swift
ios/Classes/TurfAdapters.swift
lib/src/pigeons/map_interfaces.dart
lib/src/style/style.dart
lib/src/turf_adapters.dart

This PR exposes 3 new methods which allow you to add/update/remove GeoJSONSourceFeatures. When you add identifiers associated with each feature, you can change them at runtime rather than needing to set a whole new GeoJSON object. This is especially beneficial for ``GeoJSONSource``s which host a large amount of features - in this case adding a feature can be up to 4x faster with the partial GeoJSON update API.
```dart
mapboxMap.style.addGeoJSONSourceFeatures(sourceId, dataId, features)
mapboxMap.style.updateGeoJSONSourceFeatures(sourceId, dataId, features)
mapboxMap.style.removeGeoJSONSourceFeatures(sourceId, dataId, featureIds)
```
This PR additionally updates the Draw a GeoJSON Line example to show how to use these new methods. Further, it updates `addSource` method to avoid a race …

[MAPSFLT-236] Expose Partial GeoJSON updates API 

---

.gitignore
example/android/.gitignore

Inspired by warning cleanup by @pjleonard37, this PR addresses pub pre-publishing validation  warnings related to ignored files being checked in.
I checked and it seems there is a reason to keep these files checked in, so I just removed them from gitignore:
* pubspec.lock - is recommended to be kept for applications https://dart.dev/tools/pub/glossary#lockfile
* Gradle wrappers - https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:wrapper_generation
* Podfile.lock - https://guides.cocoapods.org/using/using-cocoapods.html

Exclude checked-in files from gitignore

---

ios/Classes/StyleController.swift

This PR adds error throwing on iOS(Android is not susceptible to this) in case data -> UIImage conversion fails. Additionally, I changed `hasStyleImage` to use the dedicated method(`imageExists()`) from the platform side on iOS(Android already uses that).

Improve style image error reporting

---

.circleci/config.yml
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapInterfaceController.kt
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt
ios/Classes/Extensions.swift
ios/Classes/Generated/MapInterfaces.swift
ios/Classes/MapInterfaceController.swift
ios/Classes/StyleController.swift
lib/src/mapbox_map.dart
lib/src/pigeons/map_interfaces.dart

This PR removes `_MapWidgetDebugOptionsBox` that became useless after Pigeon started supporting collections of enums directly, so there is no need for boxing now.
Plus, fixes two minor warnings on iOS side.

Remove internal debug options boxing

---

CHANGELOG.md
android/build.gradle
example/ios/Podfile.lock
ios/mapbox_maps_flutter.podspec

Bumps Mapbox Maps SDK version to the latest stable 11.7.0.

Bump Maps SDK to 11.7.0

---

.circleci/config.yml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/pubspec.lock

This PR downgrades `androidx.lifecycle:lifecycle-runtime-ktx` to 2.6.2 bumped in https://github.com/mapbox/mapbox-maps-flutter/pull/671 to support Android Gradle Plugin(AGP) back to version 7.
The minimum supported versions:
* AGP -  `7.3.0`
* Gradle - `7.4` as per [AGP docs](https://developer.android.com/build/releases/gradle-plugin#updating-gradle)
Additionally this PR configures examples project to use the minimum supported versions of AGP and Gradle.
https://github.com/mapbox/mapbox-maps-flutter/issues/629

Fix AGP 7 compatibility

---

CHANGELOG.md
lib/src/snapshotter/snapshotter.dart

I noticed that there's a crash when opening/closing the snapshotter example repeatedly.
Upon investigation it turns out that the finalizer we use to cleanup after an instance of `Snapshotter` has been disposed doesn't have a detach token thus it never detaches which causes new instances(of `Snapshotter`) to be cleaned up together with the instances that are going away.
Fixing a rare crash in `Snapshotter`.

Fix crash after creating/destroying multiple `Snapshotter`s

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/SnapshotterMessenger.kt
example/integration_test/snapshotter/snapshotter_test.dart
example/lib/main.dart
example/lib/offline_map_example.dart
example/lib/snapshotter_example.dart
ios/Classes/Generated/SnapshotterMessenger.swift
lib/src/snapshotter/snapshotter.dart
lib/src/snapshotter/snapshotter_messenger.dart

Fixes crash in Snapshotter when GlyphsRasterizationMode is specified in MapSnapshotOptions. The crash was happening because Pigeon couldn't encode the enum, as the enum declaration was in another file. The fix was to add a reference to `GlyphsRasterizationMode` in the snapshotter template.

Fix `GlyphsRasterizationMode` crashing `Snapshotter`

---

CHANGELOG.md
lib/src/map_widget.dart

Platform view creation is asynchronous and in case widget state updates before the view is created we can get an exception trying to send a message to subscribe for events.
The fix is to ignore event subsription updates while platform view is creating.
Addresses https://github.com/mapbox/mapbox-maps-flutter/issues/657.

Ignore event subsription updates while platform view is creating

---

ios/Classes/Extensions.swift

Add availability check before using new `@retroactive` attribute.
Xcode 15 compatibility. https://github.com/mapbox/mapbox-maps-flutter/issues/745

Check for @retroactive attribute availability on iOS

---

CHANGELOG.md
example/pubspec.lock
lib/src/map_widget.dart
pubspec.yaml

This PR sets the default display back to Virtual Display on Android. Set minimum supported Flutter version to `3.22.3` and Dart to `3.4.4`. 
To address the issue map being visible for a brief moment after it has been dismissed.
https://mapbox.atlassian.net/browse/MAPSFLT-248

Virtual display hosting mode on Android

---

example/lib/map_interface_example.dart

Fixes `get/setFeatureState` actions in the map_interface_example. Source layer id was erroneously set to be the circle layer id referencing the source, while the source in question(id: `source`) is a GeoJson source that doesn't support source layering.
https://docs.mapbox.com/style-spec/reference/layers/#source-layer
Kudos to @jnorkus for uncovering this!

Fix featureState update/query in map_interface_example

---

CHANGELOG.md
lib/src/annotation/circle_annotation_manager.dart
lib/src/annotation/point_annotation_manager.dart
lib/src/annotation/polygon_annotation_manager.dart
lib/src/annotation/polyline_annotation_manager.dart

Fixes annotation click listeners not working because of missing channel prefix.
https://github.com/mapbox/mapbox-maps-flutter/issues/768

[CP] Fix annotation click listeneres

---

CHANGELOG.md
lib/src/annotation/circle_annotation_manager.dart
lib/src/annotation/point_annotation_manager.dart
lib/src/annotation/polygon_annotation_manager.dart
lib/src/annotation/polyline_annotation_manager.dart

Fixes annotation click listeners not working because of missing channel prefix.
https://github.com/mapbox/mapbox-maps-flutter/issues/768

Fix annotation click listeneres

---

lib/src/map_events.dart
lib/src/map_widget.dart

Because map widget would send event subscription request to the platform side two times during map widget initialization some events could be missed because of this. This PR fixed the issue by eliminating needless re-subscriptions.

Fix some map events not propagating to flutter side due to excessive re-subscriptions

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/AnnotationController.kt

This PR changes annotation tap propagation behavior on Android to match with iOS where taps on annotations are also propagated to the map.
https://github.com/mapbox/mapbox-maps-flutter/issues/793
https://mapbox.atlassian.net/browse/MAPSFLT-292

Align tap propagation behavior on Android and iOS.

---

example/lib/main.dart
example/lib/model_layer_interactions_example.dart

This PR adds an example for using the new Interactions API with the Model Layer as mentioned in #881 
This was needed as the Interactions API needs features in the data source for a ModelLayer to have integer identifiers in order to be recognized by it. This important point is not currently mentioned anywhere in the documentation and might cause other developers to get stuck using Interactions with Model Layer. The Mapbox AI also does not currently include this information in it's context.
Tests for this PR were not written as I believe they are not necessary for adding a simple example to the example app.

Add example for Model Layer Interactions

---

CHANGELOG.md
lib/src/style/style.dart

Fixes alpha value for colors being passed in 0...255 range instead of 0...1 on Android.
Addresses: https://github.com/mapbox/mapbox-maps-flutter/issues/915 https://mapbox.atlassian.net/browse/MAPSFLT-324

Fix incorrect color alpha value conversion on Android

---

CHANGELOG.md
android/build.gradle
example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/mapbox_maps_flutter.podspec
ios/mapbox_maps_flutter/Package.resolved
ios/mapbox_maps_flutter/Package.swift
lib/src/package_info.dart
pubspec.yaml

- Update Maps SDK dependencies to v11.12.0-rc.1 (iOS and Android)
- Bump version to v2.8.0-rc.1

Prepare v2.8.0-rc.1 release

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt

Cherry pick: https://github.com/mapbox/mapbox-maps-flutter/pull/929
This PR updates coordinate ordering on Android to use Longitude, Latitude order. This aligns with iOS, the [GeoJSON Specification](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1), and the Turf library. 
Consistency across platforms. 

Correct coordinate ordering for Android (#929)

---

.fastlane/Matchfile
Gemfile

Updates minimum Fastlane [version](https://github.com/fastlane/fastlane/releases) to the latest and adds `force_legacy_encryption: true` flag in Matchfile for compatibility. 
Avoid error with Fastlane 2.220.

Update fastlane versions

---

example/lib/animated_route_example.dart
example/lib/full_map_example.dart
example/lib/geojson_line_example.dart
example/lib/image_source_example.dart
example/lib/offline_map_example.dart
example/lib/snapshotter_example.dart
example/lib/vector_tile_source_example.dart

This PR updates our remaining examples to the Standard style with appropriate configurations. 

Update examples to Standard style

---

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/AnnotationController.kt
example/integration_test/annotations/circle_annotation_manager_test.dart
example/integration_test/annotations/point_annotation_manager_test.dart
example/integration_test/annotations/polygon_annotation_manager_test.dart
example/integration_test/annotations/polyline_annotation_manager_test.dart
example/integration_test/style/style_test.dart
example/lib/animated_route_example.dart
example/lib/circle_annotations_example.dart
example/lib/full_map_example.dart
example/lib/image_source_example.dart
example/lib/offline_map_example.dart
example/lib/snapshotter_example.dart
example/lib/vector_tile_source_example.dart
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/AnnotationController.swift
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/BaseAnnotationMessenger.swift
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/CircleAnnotationController.swift
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/PointAnnotationController.swift
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/PolygonAnnotationController.swift
ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/PolylineAnnotationController.swift

Fix annotation's gestures listeners prevent map's gestures listeners to be triggered.
Maps Flutter acts as one listener to platform's annotation gestures listener and then broadcasts the events. This means that platform's annotation will always have a listener, and in the callback where Flutter is handling these events, we always return true indicating that the gesture is being handled, this would prevent the map's gestures event to be invoked, even when Maps Flutter annotations does not have an active gesture listener. This PR addresses the issue by telling platform the gesture is not being handled when there is no listener (`sink` is not set)

do not handle annotation tap if there is no subscription

---

CHANGELOG.md
android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt

When map widget is wrapped in `GestureDetector` - multitouch gestures stops working because Flutter duplicates some motion events during gesture replay after gesture arena contest resolution.
I also created a report in Flutter's team issue tracker https://github.com/flutter/flutter/issues/176574
https://github.com/mapbox/mapbox-maps-flutter/issues/439

Workaround for duplicate move motion events on Android

---

LICENSE
README.md
android/build.gradle
example/pubspec.lock
ios/mapbox_maps_flutter.podspec
ios/mapbox_maps_flutter/Package.resolved
ios/mapbox_maps_flutter/Package.swift
lib/src/package_info.dart
pubspec.yaml

- Bump Maps SDK version to v11.16.0-rc.1 (iOS and Android)

Release v2.12.0-rc.1
