.pubignore, CHANGELOG.md, README.md, android/build.gradle, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/ProxyBinaryMessenger.kt, example/ios/Podfile.lock, example/pubspec.lock, ios/Classes/MapboxMapController.swift, ios/mapbox_maps_flutter.podspec, lib/mapbox_maps_flutter.dart, lib/src/annotation/annotation_manager.dart, lib/src/annotation/circle_annotation_manager.dart, lib/src/annotation/point_annotation_manager.dart, lib/src/annotation/polygon_annotation_manager.dart, lib/src/annotation/polyline_annotation_manager.dart, lib/src/map_widget.dart, lib/src/mapbox_map.dart, lib/src/mapbox_maps_platform.dart, lib/src/proxy_binary_messenger.dart
Pigeon does not support generating separate instances of api [at the moment](https://github.com/flutter/flutter/issues/66710). 
Thus to separate the channels I've appended suffix ("/map_${id}") at the BinaryMessenger level in ProxyBinaryMessenger.
Fixes #17, #54
=> Fix multimap issues.

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/GestureController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt, ios/Classes/CompassController.swift, ios/Classes/Extensions.swift, ios/Classes/GesturesController.swift, ios/Classes/LocationController.swift, ios/Classes/MapboxMapController.swift, ios/Classes/MapboxMapFactory.swift, ios/Classes/PointAnnotationController.swift, ios/Classes/StyleController.swift, lib/src/mapbox_map.dart, lib/src/mapbox_maps_platform.dart, lib/src/pigeons/map_interfaces.dart, lib/src/pigeons/settings.dart
Multiple small fixes, mainly mappings : 
iOS 
- Apply scale factor to UIImage.
- Apply scale factor to UIEdgeInsets.
- Fix vertical scrollMode lock on gesture settings update.
Android 
- Fix ImageStretches mapping.
=> Various fixes.

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart
Updated platform dependencies, bumped flutter plugin version.
=> Update Maps SDK to 10.13, bump version.

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart
This PR add changelog for 0.4.5 release and bumps the library version to 0.4.5.
=> Prepare 0.4.5 release

android/build.gradle
Fix registry token lookup failing with an unrelated error in certain circumstances.
=> Registry token lookup

android/src/main/java/com/mapbox/maps/pigeons/FLTMapInterfaces.java, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/CameraController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt, example/integration_test/camera_test.dart, example/lib/camera.dart, example/lib/full_map.dart, ios/Classes/CameraController.swift, ios/Classes/MapInterfaces.h, ios/Classes/MapInterfaces.m, lib/src/events.dart, lib/src/mapbox_map.dart, lib/src/pigeons/gesture_listeners.dart, lib/src/pigeons/map_interfaces.dart
Add method `cameraForCoordinates:camera:coordinatesPadding:maxZoom:offset`
=> Update v11 Camera positions API

example/integration_test/camera_test.dart, example/integration_test/style/layer/background_layer_test.dart, example/integration_test/style/layer/circle_layer_test.dart, example/integration_test/style/layer/fill_extrusion_layer_test.dart, example/integration_test/style/layer/fill_layer_test.dart, example/integration_test/style/layer/heatmap_layer_test.dart, example/integration_test/style/layer/hillshade_layer_test.dart, example/integration_test/style/layer/line_layer_test.dart, example/integration_test/style/layer/location_indicator_layer_test.dart, example/integration_test/style/layer/raster_layer_test.dart, example/integration_test/style/layer/sky_layer_test.dart, example/integration_test/style/layer/symbol_layer_test.dart, example/integration_test/style/style_test.dart, lib/src/mapbox_map.dart, lib/src/style/layer/background_layer.dart, lib/src/style/layer/circle_layer.dart, lib/src/style/layer/fill_extrusion_layer.dart, lib/src/style/layer/fill_layer.dart, lib/src/style/layer/heatmap_layer.dart, lib/src/style/layer/hillshade_layer.dart, lib/src/style/layer/line_layer.dart, lib/src/style/layer/location_indicator_layer.dart, lib/src/style/layer/raster_layer.dart, lib/src/style/layer/sky_layer.dart, lib/src/style/layer/symbol_layer.dart, lib/src/style/mapbox_styles.dart, lib/src/style/style.dart
- Add `slot` to Layer abstract class. Also defined list of slot constant value (top, middle, and bottom)
- Add integration tests
=> Support Layer Slot

CHANGELOG.md, android/build.gradle, example/integration_test/style/style_test.dart, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec
Updates Mapbox Maps Android and iOS dependencies to v11.1.0
=> Bump Mapbox Maps SDK to v11.1

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> bump mapbox-maps-flutter to v1.0.0-beta.2

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt
=> fix MapOptions creation invalid index access

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.yaml, ios/mapbox_maps_flutter.podspec
Bumps Maps SDK dependency to v11.2.0-beta.1
Bringing new features and bug fixes onboard.
=> Maps SDK 11.2.0-beta.1

CHANGELOG.md, README.md, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bumps plugin version to 1.0.0-beta.3
=> Prepare 1.0.0-beta.3

CHANGELOG.md, example/lib/full_map.dart, ios/Classes/MapEvents+JSON.swift, lib/src/callbacks.dart, lib/src/events.dart, lib/src/map_widget.dart, lib/src/mapbox_map.dart, lib/src/mapbox_maps_platform.dart, test/events_test.dart
Adds `MapWidget.onResourceRequestListener` to enable listening for map resource loading events.
Parity with platforms.
Not testable currently.
=> Add onResourceRequestListener

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle
Applies extended debug environment for Android platform.
Enabling extended debug capabilities.
=> Apply extended debug environment during android build

example/integration_test/map_interface_test.dart
Tests for https://github.com/mapbox/mapbox-maps-flutter/pull/420
Tests appeared to be flaky(or Firebase Test Lab has issues).
=> Add tests for mapbox options

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxOptionsController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt, example/integration_test/map_interface_test.dart, ios/Classes/Generated/MapInterfaces.swift, ios/Classes/MapboxOptionsController.swift, lib/src/mapbox_maps_options.dart, lib/src/pigeons/map_interfaces.dart
Exposes configuration options for setting map's worldview and language.
Adding missing configuration options.
Addresses https://mapbox.atlassian.net/browse/MAPSFLT-183
https://github.com/mapbox/mapbox-maps-flutter/pull/421
=> i18n settings

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bumps version number to 1.0.0 in the main branch
=> Bump version number to 1.0.0

example/lib/circle_annotations.dart, example/lib/cluster.dart, example/lib/geojson_line.dart, example/lib/point_annotations.dart, example/lib/polygon_annotations.dart, example/lib/polyline_annotations.dart
This PR updates the starting camera for a few PRs so they start in more logical places. It also fixes the image for one example (geojson_line.dart). 
Makes the examples easier to use.
=> Updates starting cameras for several examples 

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/turf/TurfAdapters.kt, ios/Classes/MapboxMapFactory.swift
Fixes camera center not being deserialized properly upon platform view creation.
https://mapbox.atlassian.net/browse/MAPSFLT-197 and https://github.com/mapbox/mapbox-maps-flutter/issues/464
=> Fix camera center not being deserialized properly upon platform view creation

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Updates versions to prepare for v1.1.0-rc.1 release.
=> Update versions for v1.1.0-rc.1 release

CHANGELOG.md, lib/src/mapbox_maps_options.dart
Cherry-picks the Mark worldview and language configs as experimental commit to the release branch
=> Cherry-pick Mark worldview and language configs as experimental to the release branch

ios/Classes/CircleAnnotationController.swift, ios/Classes/PointAnnotationController.swift, ios/Classes/PolygonAnnotationController.swift, ios/Classes/PolylineAnnotationController.swift
Fixes point annotation images not being shown on iOS.
https://github.com/mapbox/mapbox-maps-flutter/issues/457 and https://mapbox.atlassian.net/issues/MAPSFLT-196
=> Fix point annotation image not being shown

CHANGELOG.md, android/build.gradle, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapsPlugin.kt
Cherry-pick https://github.com/mapbox/mapbox-maps-flutter/pull/478 into `release/v1.0`
=> [CP] Fix crash due to lifecycle plugin

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, ios/Classes/MapboxMapController.swift
Fixes usage analytics reporting by providing plugin-specific fragment of user-agent header field.
https://mapbox.atlassian.net/browse/MAPSFLT-201
=> Fix plugin usage analytics

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, ios/Classes/MapboxMapController.swift
Cherry-pick of https://github.com/mapbox/mapbox-maps-flutter/pull/483 to v1.0
=> [CP] Analytics fix

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/CompassMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LocationComponentMappings.kt, example/lib/location.dart, lib/src/style/style.dart
Updates formatting from codegen
=> Make minor codegen updates

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec
Updates platform Maps SDK dependencies to 11.3.0.
=> Bump Maps SDK to 11.3.0

CHANGELOG.md, ios/Classes/MapEvents+JSON.swift
Cherry-pick of https://github.com/mapbox/mapbox-maps-flutter/pull/440 into v1.1.0
=> [CP] Fix crash in `onStyleImageMissingListener`

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/pubspec.lock, ios/mapbox_maps_flutter.podspec
Cherry-pick of https://github.com/mapbox/mapbox-maps-flutter/pull/482 to release/v1.0
=> [CP] 11.3.0 SDK version bump

CHANGELOG.md, README.md, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Updates plugin version to 1.1.0.
Preparation for the release.
=> Bump plugin version to 1.1.0

CHANGELOG.md, README.md, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Cherry pick of https://github.com/mapbox/mapbox-maps-flutter/pull/487 into release/v1.0
=> [CP] Bump plugin version to 1.1.0

android/build.gradle
Ingest https://github.com/mapbox/mapbox-maps-flutter/pull/221
=> Look up the sdk download token at MAPBOX_DOWNLOADS_TOKEN too (#221)

example/lib/geojson_line.dart
Ingest https://github.com/mapbox/mapbox-maps-flutter/pull/203/
=> Fix geojson line example

lib/src/style/layer/background_layer.dart, lib/src/style/layer/circle_layer.dart, lib/src/style/layer/fill_extrusion_layer.dart, lib/src/style/layer/fill_layer.dart, lib/src/style/layer/heatmap_layer.dart, lib/src/style/layer/hillshade_layer.dart, lib/src/style/layer/line_layer.dart, lib/src/style/layer/location_indicator_layer.dart, lib/src/style/layer/raster_layer.dart, lib/src/style/layer/sky_layer.dart, lib/src/style/layer/symbol_layer.dart, lib/src/style/source/geojson_source.dart, lib/src/style/source/image_source.dart, lib/src/style/source/raster_source.dart, lib/src/style/source/rasterdem_source.dart, lib/src/style/source/vector_source.dart
Ingest https://github.com/mapbox/mapbox-maps-flutter/pull/246
=> Declare explicit types in layers and sources (#246)

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Prepare for v2.0.0-beta.1 release.
=> Update to v2.0.0-beta.1

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Prepare 2.0.0-rc.1

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapFactory.kt, ios/Classes/MapboxMapFactory.swift
Triggers feature telemetry counter increment each time a `MapView` is created.
Collecting anonymous feature telemetry. Addresses https://mapbox.atlassian.net/browse/MAPSFLT-215
=> Map feature telemetry

example/integration_test/all_test.dart
Adds raster array tests to the default collection of tests.
=> Add raster array source tests to the default test suite

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bumps the plugin version to 2.0.0
=> Bump plugin version to 2.0.0

.circleci/config.yml, CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt, example/integration_test/style/layer/model_layer_test.dart, example/ios/Podfile.lock, example/lib/main.dart, example/lib/model_layer.dart, ios/Classes/Extensions.swift, ios/Classes/Generated/MapInterfaces.swift, ios/Classes/StyleController.swift, lib/mapbox_maps_flutter.dart, lib/src/pigeons/map_interfaces.dart, lib/src/style/layer/model_layer.dart
Adds ModelLayer
ModelLayer is out of the experimental API and can be used in the Flutter SDK now
MAPSFLT-167
<image height=600 src="https://github.com/mapbox/mapbox-maps-flutter/assets/735178/93133e07-2dc9-4e8f-9c2d-efbb2245d00a" />
=> Add ModelLayer support

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/CompassMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/GesturesMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LocationComponentMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LogoMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/ScaleBarMappings.kt
In https://github.com/mapbox/mapbox-maps-flutter/pull/536 `AttributionMappings.kt` and `LogoMappings.kt` were updated to perform Flutter->platform updates in a single batch. This PR applies the same approach to the rest of the settings controllers.
Consistent approach across similar components.
=> Bulk update all settings on Android

CHANGELOG.md, README.md, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Bump version to 2.1.0-beta.1

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/OfflineController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/TileStoreController.kt
Fix https://github.com/mapbox/mapbox-maps-flutter/issues/585
=> [android] call endOfStream on ui thread

CHANGELOG.md, README.md, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Bump SDK version to 2.1.0-rc.1

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec
Bumps Maps SDK to the latest 11.5.0 version.
=> Bump Maps SDK to 11.5.0

LICENSE, README.md, example/README.md, example/pubspec.yaml, pubspec.yaml
Replaces all references to the SDK as a "plugin" with "SDK".
=> Replace plugin references with SDK.

.circleci/config.yml
Print more logs to help diagnose occasional [build issues](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-flutter/776/workflows/fd4a4c9b-a6cc-46b5-b81a-86d779eb455b/jobs/2607).
=> Print stacktrace on issue.

android/gradle.properties, example/android/gradle.properties
Increase Xmx to avoid build OOM issues on Android
=> Add more Xmx memory to avoid build OOM.

CHANGELOG.md, lib/src/style/mapbox_styles.dart
=> Expose Mapbox Standard Satellite style

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bumps Maps SDK version to 11.6.0-rc.1 and Flutter SDK version to 2.2.0-rc.1
=> Prepare 2.2.0-rc.1 release

README.md
Updates README for clarity and with links to new documentation.
=> Update README with additional documenation

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
* bump deps to v11.6.0
* bump version to v2.2.0
=> Prepare v2.2.0 release (#655)

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt
=> fixes build for flutter 3.24.1

CHANGELOG.md, README.md, android/build.gradle, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/OfflineMapInstanceManager.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/offline/TileStoreController.kt, example/ios/Podfile.lock, example/lib/offline_map.dart, example/pubspec.lock, ios/Classes/Extensions.swift, ios/Classes/Offline/OfflineMapInstanceManager.swift, ios/Classes/Offline/TileStoreController.swift, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Prepare 2.2.1 release

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/lib/cluster.dart, example/lib/map_interface.dart, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Prepare 2.3.0-beta.1

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, lib/src/mapbox_map.dart, lib/src/mapbox_maps_platform.dart
Add experimental MapView.setSnapshotLegacyMode function to help avoiding MapView.snapshot native crash on some Samsung devices running Android 14
=> feat: add setSnapshotLegacyMode function

android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec
=> Bump Maps SDK version to 11.7.0-rc.1

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Bump SDK version to 2.3.0-rc.1

CHANGELOG.md, example/lib/full_map.dart, ios/Classes/MapEvents+JSON.swift, lib/mapbox_maps_flutter.dart, lib/src/events.dart, lib/src/extensions.dart, test/events_test.dart
- Expose `CameraChanged/cameraState`
- Address #649 #648
=> Expose CameraChanged/cameraState

CHANGELOG.md, README.md, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bumps SDK version to 2.3.0 + changelog update.
=> Prepare 2.3.0

.circleci/config.yml, CHANGELOG.md, README.md, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapInterfaceController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/integration_test/map_interface_test.dart, example/ios/Podfile.lock, example/lib/cluster.dart, example/lib/map_interface.dart, example/pubspec.lock, ios/Classes/Generated/MapInterfaces.swift, ios/Classes/MapInterfaceController.swift, ios/Classes/StyleController.swift, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, lib/src/mapbox_map.dart, lib/src/pigeons/map_interfaces.dart, pubspec.yaml
Cherry-picks relevant changes from `main` to `release/v2.3` for `2.3.0` release.
Mapbox Maps Flutter SDK v2.3.0 release.
=> `2.3.0` release cherry-picks

example/lib/offline_map_example.dart
This PR fixes offline map example crashing when closing it immediately after opening.
=> Fix offline example crashing when closed immediately

example/lib/animated_route_example.dart, example/lib/animation_example.dart, example/lib/camera_example.dart, example/lib/circle_annotations_example.dart, example/lib/cluster_example.dart, example/lib/debug_options_example.dart, example/lib/example.dart, example/lib/full_map_example.dart, example/lib/geojson_line_example.dart, example/lib/gestures_example.dart, example/lib/image_source_example.dart, example/lib/location_example.dart, example/lib/main.dart, example/lib/map_interface_example.dart, example/lib/model_layer_example.dart, example/lib/offline_map_example.dart, example/lib/ornaments_example.dart, example/lib/point_annotations_example.dart, example/lib/polygon_annotations_example.dart, example/lib/polyline_annotations_example.dart, example/lib/projection_example.dart, example/lib/snapshotter_example.dart, example/lib/style_example.dart, example/lib/tile_json_example.dart, example/lib/traffic_route_line_example.dart, example/lib/vector_tile_source_example.dart
Adds subtitles to the example list.
=> Example subtitles

.circleci/config.yml
=> Add slack notifications for CI failures on main and release

.circleci/config.yml
=> Fix tag display in Slack CI template

.circleci/config.yml
This PR adds `sanity-check` CI job, the job invokes `dart analyze` failing if any analysis errors are detected.
=> CI sanity check

.github/CODEOWNERS
=> Set maps-flutter team as codeowner

.circleci/config.yml, example/integration_test/all_test.dart, scripts/check_test_suite.dart
This PR adds snapshotter tests to the aggregate test suite(`all_test.dart`).
In order to avoid this in the future this PR adds a step to check for all test files to be included to the aggregate test suite.
=> Test suite check

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
This PR makes all preparations for 2.4.0-beta.1.
=> Prepare for 2.4.0-beta.1

README.md
This PR removes instructions for secret access token setup from the readme since it is not required anymore.
=> Update README for secret access token removal

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, ios/mapbox_maps_flutter.podspec
Updates Maps SDK dependency to the latest version 11.8.0-rc.1.
=> Bump MapsSDK to 11.8.0-rc.1

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapInterfaceController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt, example/integration_test/map_interface_test.dart, example/integration_test/snapshotter/snapshotter_test.dart, example/ios/Podfile.lock, example/lib/traffic_route_line_example.dart, example/pubspec.lock, ios/Classes/Generated/MapInterfaces.swift, ios/Classes/MapInterfaceController.swift, lib/src/annotation/annotation_manager.dart, lib/src/mapbox_map.dart, lib/src/offline/offline_manager.dart, lib/src/offline/tile_store.dart, lib/src/pigeons/map_interfaces.dart
This PR introduces a new experimental property `MapboxMap.styleGlyphURL`.
https://mapbox.atlassian.net/browse/MAPSFLT-254
=> Add `styleGlyphURL` property

CHANGELOG.md, README.md, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bump SDK version to 2.4.0-rc.1.
=> Bump SDK version to `2.4.0-rc.1`

README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
=> Bump version to 2.4.1

README.md, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
CP https://github.com/mapbox/mapbox-maps-flutter/pull/778 to main.
=> [CP] Bump version to 2.4.1

android/build.gradle
Removes internal check in `build.gradle` for the secret token.
=> Remove secret token requirement from Android side

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt
Fixes buffer underflow exception when trying to get style image added programmatically on Android.
=> Fix image underflow exception on android

CHANGELOG.md, README.md, android/build.gradle, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/StyleController.kt, example/ios/Podfile.lock, example/pubspec.lock, ios/Classes/PointAnnotationController.swift, ios/Classes/PolylineAnnotationController.swift, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, lib/src/style/layer/symbol_layer.dart, pubspec.yaml
This PR updates necessary versions for the v2.5.0-beta.1 release. In particular, note that Turf has been updated to v4.0.0-beta.1. Also note that some small code changes were necessary to use experimental features.
=> Update versions for v2.5.0-beta.1 release 

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
Bump Maps SDK dependencies to 11.9.0-beta.1 and bump the SDK version to 2.5.0-rc.1.
=> Prepare release 2.5.0-rc.1

lib/src/map_events.dart, lib/src/map_widget.dart
CP of https://github.com/mapbox/mapbox-maps-flutter/pull/804 to `release/v2.5` branch.
=> [CP] Event subscription fix to `release/v2.5`

android/src/main/kotlin/com/mapbox/maps/mapbox_maps/ViewportController.kt
CP https://github.com/mapbox/mapbox-maps-flutter/pull/812 into `release/v2.5` branch
=> [CP] Viewport Android exception fix

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/Settings.kt, ios/Classes/Generated/Settings.swift, lib/src/pigeons/settings.dart, lib/src/style/layer/clip_layer.dart
Marks `ClipLayer` stable according to the latest style spec update.
=> Mark `ClipLayer` as stable

lib/src/extensions.dart
Fix a warning found during publishing.
=> Fix lint warning

CHANGELOG.md, README.md, android/build.gradle, example/ios/Flutter/AppFrameworkInfo.plist, example/ios/Podfile, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/EnumsMapping.swift, lib/src/package_info.dart, pubspec.yaml
This PR updates necessary versions for the v2.6.0-beta.1 release. In particular, note that the iOS minimum is now 14.0. Also note that an experimental import was necessary to use experimental features.
=> Update versions for v2.6.0-beta.1 release 

README.md
=> Update README.md for viewport support

README.md
Updates README with edits from @shinriyo:
> it is not nullable
> and it is Point object
=> Update README.md (#837)

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.swift
Bumps Android and iOS dependencies versions to 11.10.0-rc.1
=> Bump platform SDKs version

CHANGELOG.md, README.md, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/package_info.dart, pubspec.yaml
=> Bump SDK version to `2.6.0-rc.1`

CHANGELOG.md, README.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, lib/src/map_widget.dart, pubspec.yaml
* Bumps MapsSDK dependency to `11.9.2` on both platforms.
* Bumps the SDK version to `2.5.2`.
=> Prepare release `2.5.2`

CHANGELOG.md
CP changes form https://github.com/mapbox/mapbox-maps-flutter/pull/858 to `main`, version conflicts were resolved in favor of `main`.
=> [CP] Prepare release 2.5.2 to main

CHANGELOG.md, example/lib/standard_style_interactions_example.dart, ios/mapbox_maps_flutter.podspec, lib/src/style/interactive_features/standard_buildings.dart, lib/src/style/interactive_features/standard_place_labels.dart, lib/src/style/interactive_features/standard_poi.dart
This PR includes some formatting updates now that these Standard types are generated by templates (see internal PR). 
Generating our types makes maintenance and alignment easier.
=> Updates generated code created by templates 

example/integration_test/interactive_features_test.dart, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/MapInterfaceController.swift
Adds dispatch implementation back and the related tests. Will be ready to merge once iOS v11.10.0 stable is released.
=> Add iOS tests back, add dispatch implementation

CHANGELOG.md, README.md, ios/mapbox_maps_flutter.podspec, lib/src/package_info.dart, pubspec.yaml
Update version and changelog for 2.7.0-beta.1
=> Update version and changelog

README.md
Fixes a dead link.
Dead links bad. Working links good.
- [ N/A -> I'm assuming this is too minor for a version bump ] Add a changelog entry.
- [ N/A -> No code changes ] Write tests for all new functionality. If tests were not written, please explain why.
- [ N/A -> No code changes ] Add documentation comments for any added or updated public APIs.
=> fix: dead link

example/lib/main.dart, example/lib/model_layer_example.dart, example/lib/model_layer_interactions_example.dart
Original PR by @m4dhav [here](https://github.com/mapbox/mapbox-maps-flutter/pull/889).
This PR adds a new example that shows how to add interactions to a Model Layer. Additionally, it updates our old Model Layer example, which did not add the car model properly.
=> Add Model Layer Interactions Example

CHANGELOG.md, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
- Bump Maps SDK to 11.10.2 (iOS) and 11.10.3 (Android)
=> Prepare release v2.6.2

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, example/pubspec.lock, example/pubspec.yaml
Removes crash operator(`!!`) from resetting lifecycle listener on map view in `onFlutterViewDetached` method. Also, I added resetting the lifecycle before map view is disposed.
https://mapbox.atlassian.net/browse/MAPSFLT-315
=> Fix NPE in onFlutterViewDetached

CHANGELOG.md, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
=> Prepare 2.7.0 release

CHANGELOG.md, README.md, android/build.gradle, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/MapboxMapController.kt, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, example/pubspec.yaml, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
CP https://github.com/mapbox/mapbox-maps-flutter/pull/904 and https://github.com/mapbox/mapbox-maps-flutter/pull/905 into `release/v2.7` branch.
=> [CP] [release/v2.7] Prepare `2.7.0` release

CHANGELOG.md, lib/src/style/style.dart
CP https://github.com/mapbox/mapbox-maps-flutter/pull/919 into `release/v2.8` branch.
=> [CP] Fix incorrect color alpha value conversion on Android

lib/src/mapbox_map.dart
=> Update startPerformanceStatisticsCollection documentation

lib/src/mapbox_map.dart
CP https://github.com/mapbox/mapbox-maps-flutter/pull/921 into `release/v2.8`
=> [CP] Update startPerformanceStatisticsCollection documentation

.circleci/config.yml, LICENSE, scripts/license.sh
Introduces a script to generate/validate license file, plus adds license validation to sanity check on CI.
https://mapbox.atlassian.net/browse/MAPSFLT-323
=> Generate license

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Update versions for v2.8.0 release. 
=> Prepare 2.8.0 Release

.circleci/config.yml, CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml, scripts/license.sh
Cherry-picks in the license update and 2.8.0 stable release updates. 
=> Update versions for 2.8.0 release

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LocationComponentMappings.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/MapInterfaces.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/Settings.kt, example/integration_test/location_test.dart, example/lib/standard_style_interactions_example.dart, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/GestureListeners.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/MapInterfaces.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/OfflineMessenger.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/PerformaceStatistics.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/Settings.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/SnapshotterMessenger.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/ViewportInternal.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/LocationController.swift, lib/src/annotation/point_annotation_manager.dart, lib/src/annotation/polygon_annotation_manager.dart, lib/src/annotation/polyline_annotation_manager.dart, lib/src/mapbox_map.dart, lib/src/pigeons/map_interfaces.dart, lib/src/pigeons/settings.dart, lib/src/style/mapbox_styles.dart
This PR promotes the Interactions API to stable at the Flutter level. The following APIs are now stable:
* `MapboxMap.addInteraction`
* `MapboxMap.removeInteraction`
* `MapboxMap.setFeatureStateForFeaturesetDescriptor`
* `MapboxMap.setFeatureStateForFeaturesetFeature`
* `MapboxMap.getFeatureStateForFeaturesetDescriptor`
* `MapboxMap.getFeatureStateForFeaturesetFeature`
* `MapboxMap.removeFeatureStateForFeaturesetDescriptor`
* `MapboxMap.removeFeatureStateForFeaturesetFeature`
* `MapboxMap.resetFeatureStatesForFeatureset`
* `MapboxMap.queryRenderedFeaturesForFeatureset`
* Additionally, the STANDARD_EXPERIMENTAL style has been removed
Additional formatting updates are included as well as moving `modelElevationReference` to `LocationPuck3D`. 
PRs must be submitted under the terms of our …
=> Promote Interactions APIs to stable

CHANGELOG.md
CP updates to Changelog for consistency 
=> Update CHANGELOG.md (#952)

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/CircleAnnotationController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/CircleAnnotationEnumsExtensions.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/annotation/PolygonAnnotationController.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/CircleAnnotationMessenger.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PointAnnotationMessenger.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PolygonAnnotationMessenger.kt, example/integration_test/annotations/circle_annotation_manager_test.dart, example/integration_test/annotations/polygon_annotation_manager_test.dart, example/integration_test/annotations/polygon_annotation_test.dart, example/integration_test/style/layer/circle_layer_test.dart, example/integration_test/style/layer/fill_layer_test.dart, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/CircleAnnotationController.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Annotations/PolygonAnnotationController.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/EnumsMapping.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/CircleAnnotationMessenger.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/PointAnnotationMessenger.swift, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/PolygonAnnotationMessenger.swift, lib/src/annotation/circle_annotation_manager.dart, lib/src/annotation/point_annotation_manager.dart, lib/src/annotation/polygon_annotation_manager.dart, lib/src/pigeons/circle_annotation_messenger.dart, lib/src/pigeons/point_annotation_messenger.dart, lib/src/pigeons/polygon_annotation_messenger.dart, lib/src/style/layer/circle_layer.dart, lib/src/style/layer/fill_layer.dart, lib/src/style/layer/symbol_layer.dart
This PR updates our generated code, adding new experimental properties: 
- FillLayer.fillConstructBridgeGuardRail
- FillLayer.fillBridgeGuardRailColor
- FillLayer.fillTunnelStructureColor
- CircleLayer.circleElevationReference
Alignment with iOS and Android 
=> Add new properties on FillLayer and CircleLayer

example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/lib/standard_style_import_example.dart
Adds a toggle to our Standard example demonstrating how to toggle landmark icons. 
https://github.com/user-attachments/assets/46661c10-a51f-4f93-9ffe-b473ac26fa84
=> Add landmark icon toggle to example

.circleci/config.yml
https://circleci.com/developer/images/image/cimg/python
=> Update cimg/python of firebase-test-runner to 3.13

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Updates versions for v2.9.0 stable release.
=> Update versions for 2.9.0 stable

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Prepares release 2.10.0-beta.1.
=> Bump Maps SDK to 11.14.0-beta.1, bump version to 2.10.0-beta.1

CHANGELOG.md, android/build.gradle, scripts/license.sh
CP https://github.com/mapbox/mapbox-maps-flutter/pull/985 into `release/v2.10`.
=> [CP] NDK 27/16KB page size support

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/GestureListeners.kt, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/pigeons/PointAnnotationMessenger.kt, ios/mapbox_maps_flutter/Sources/mapbox_maps_flutter/Classes/Generated/GestureListeners.swift, lib/src/pigeons/gesture_listeners.dart
=> Fix crash when receiving annotation interactions (#989)

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Bumps SDK version to 2.8.1, bumps Maps SDK native dependency versions to the latest 11.12 patches.
=> Prepare 2.8.1 release

CHANGELOG.md, android/build.gradle, scripts/license.sh
This reverts commit 80cfd127b633862815c05cc49f53fe8ea52ffe2f.
We are pushing this change for 2.11.
=> [release/v2.10] NDK 27 revert

CHANGELOG.md, README.md, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Updates versions for v2.6.3 (only iOS version updates needed)
=> Update iOS versions

CHANGELOG.md, android/src/main/kotlin/com/mapbox/maps/mapbox_maps/Extentions.kt, example/integration_test/style/style_test.dart, example/pubspec.lock
- Fixes minor bug on Android where expressions were not being properly evaluated. Fix is to convert List expressions starting with strings to JSON format.
- Avoid a crash 
=> Update Android Expression handling

.circleci/config.yml, CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/android/app/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml, scripts/license.sh
* Update Maps SDK to 11.15.0-beta.1
* Bump version to 2.11.0-beta.1
=> Prepare `2.11.0-beta.1`

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/pubspec.lock, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
- Bump Maps SDK to v11.15.0-rc.1
=> Prepare v2.11.0-rc.1

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
=> Update versions for v2.11.0 release (#1027)

CHANGELOG.md, android/build.gradle, scripts/license.sh
Restores 16 KB page support in the default distribution.
=> Reapply "Use Maps SDK Android dependency with NDK 27 support (#985)"

CHANGELOG.md, LICENSE, README.md, android/build.gradle, example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/mapbox_maps_flutter.podspec, ios/mapbox_maps_flutter/Package.resolved, ios/mapbox_maps_flutter/Package.swift, lib/src/package_info.dart, pubspec.yaml
Update versions and changelog for v2.10.1 release
=> Update versions for 2.10.1 release
